"""Change user name fields to string from unicode

Revision ID: 1947d4fddd60
Revises: e7679039901
Create Date: 2015-07-09 11:26:22.287421

"""

# revision identifiers, used by Alembic.
revision = '1947d4fddd60'
down_revision = 'e7679039901'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
