"""Remove middle name field from users

Revision ID: 3fa973bc530
Revises: 7815e0e8ad3
Create Date: 2015-07-09 11:27:48.128539

"""

# revision identifiers, used by Alembic.
revision = '3fa973bc530'
down_revision = '7815e0e8ad3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'middlename')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middlename', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
