"""Added middle name field to users

Revision ID: 7815e0e8ad3
Revises: 1947d4fddd60
Create Date: 2015-07-09 11:27:18.074182

"""

# revision identifiers, used by Alembic.
revision = '7815e0e8ad3'
down_revision = '1947d4fddd60'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('middlename', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'middlename')
    ### end Alembic commands ###
