"""Initial db creation

Revision ID: e7679039901
Revises: 
Create Date: 2015-07-09 11:24:30.218381

"""

# revision identifiers, used by Alembic.
revision = 'e7679039901'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('firstname', sa.Unicode(length=255), nullable=True),
    sa.Column('lastname', sa.Unicode(length=255), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('registeredOn', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('job', sa.String(), nullable=True),
    sa.Column('major_skill', sa.Unicode(length=50), nullable=True),
    sa.Column('other_skills', postgresql.JSON(), nullable=True),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('had_known', sa.String(), nullable=True),
    sa.Column('advice', sa.String(), nullable=True),
    sa.Column('social_website', sa.String(), nullable=True),
    sa.Column('social_linkedin', sa.String(), nullable=True),
    sa.Column('social_twitter', sa.String(), nullable=True),
    sa.Column('social_github', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
